EatPic/EatPic-Spring

- src/main/java/EatPic/spring/domain/calendar/controller/CalendarController.java
- src/main/java/EatPic/spring/domain/calendar/dto/CalendarDayResponse.java
- src/main/java/EatPic/spring/domain/calendar/service/CalendarService.java
- src/main/java/EatPic/spring/domain/card/entity/Card.java
- src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
> ex) #15 
> 사용자의 이번 달 및 전달 기록을 불러옵니다.
> 기록이 있는 날짜에는 해당 날의 첫 번째 식사의 대표 이미지를 함께 반환합니다.
> 캘린더 무한 스크롤을 위한 이전 달 조회에도 사용됩니다.
> 로그인/회원가입 부분은 안입힘 (주석처리 참고)
> Feat: Calendar 기능 API 추가

- src/main/java/EatPic/spring/domain/card/controller/CardController.java
- src/main/java/EatPic/spring/domain/card/converter/CardConverter.java
- src/main/java/EatPic/spring/domain/card/dto/response/CardResponse.java
- src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
- src/main/java/EatPic/spring/domain/card/service/CardService.java
- src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
- src/main/java/EatPic/spring/domain/user/controller/UserRestController.java
- src/main/java/EatPic/spring/domain/user/converter/UserConverter.java
- src/main/java/EatPic/spring/domain/user/dto/response/UserResponseDTO.java
- src/main/java/EatPic/spring/domain/user/repository/UserFollowRepository.java
- src/main/java/EatPic/spring/domain/user/service/UserService.java
> 66
* 프로필 화면 텍스트 정보(이름, 팔로워 수 등)조회 api
* 프로필 화면 피드 미리보기(카드) 조회 api
>
>
> Feat: 프로필 화면 API

- src/main/java/EatPic/spring/domain/card/controller/CardController.java
- src/main/java/EatPic/spring/domain/card/converter/CardConverter.java
- src/main/java/EatPic/spring/domain/card/dto/response/CardResponse.java
- src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
- src/main/java/EatPic/spring/domain/card/service/CardService.java
- src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
- src/main/java/EatPic/spring/global/common/code/status/ErrorStatus.java
> Feat: 커뮤니티 피드 조회하기

- src/main/java/EatPic/spring/domain/user/controller/UserController.java
- src/main/java/EatPic/spring/domain/user/converter/UserConverter.java
- src/main/java/EatPic/spring/domain/user/dto/request/SignupRequestDTO.java
- src/main/java/EatPic/spring/domain/user/service/UserService.java
> #108 
> passwordMatching 제거
> role, notificationAgreed 추가에 따른 controller, service  수정
> Feat: 이메일 회원 가입

- .gitignore
- src/main/java/EatPic/spring/domain/card/controller/SearchController.java
- src/main/java/EatPic/spring/domain/card/converter/CardConverter.java
- src/main/java/EatPic/spring/domain/card/dto/request/CardCreateRequest.java
- src/main/java/EatPic/spring/domain/card/dto/response/SearchResponseDTO.java
- src/main/java/EatPic/spring/domain/card/entity/Card.java
- src/main/java/EatPic/spring/domain/card/repository/CardHashtagRepository.java
- src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
- src/main/java/EatPic/spring/domain/card/repository/HashtagRepository.java
- src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
- src/main/java/EatPic/spring/domain/card/service/SearchService.java
- src/main/java/EatPic/spring/domain/card/service/SearchServiceImpl.java
> ex) #41
> 기본 해시태그들은 데이터를 깔아둔 상태입니다.
> 아, 참고로 저희 user_id 1인 유저는 ADMIN으로 두고 사용합니다.
> 검색할 때는 해시태그명으로 검색을 하고 해시태그명을 포함한 저장된 게시글(카드)들의 개수를 세서 card_count로 반환합니다.
> Feat: 검색 범위가 전체인 경우에서 해시태그 검색하기

- src/main/java/EatPic/spring/domain/user/controller/UserController.java
- src/main/java/EatPic/spring/domain/user/service/UserService.java
- src/main/java/EatPic/spring/domain/user/service/UserServiceImpl.java
> #50 
> 유저 아이디 (nameId) 중복 검사
-> 아이디 중복 시
-> 아이디 중복 아닐 시
> Feat: 유저 아이디(nameId) 중복 검사 

- src/main/java/EatPic/spring/domain/bookmark/controller/BookmarkController.java
- src/main/java/EatPic/spring/domain/bookmark/service/BookmarkService.java
- src/main/java/EatPic/spring/domain/bookmark/service/BookmarkServiceImpl.java
- src/main/java/EatPic/spring/domain/card/controller/CardController.java
- src/main/java/EatPic/spring/domain/card/service/CardService.java
- src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
- src/main/java/EatPic/spring/domain/comment/controller/CommentRestController.java
- src/main/java/EatPic/spring/domain/comment/service/CommentService.java
- src/main/java/EatPic/spring/domain/comment/service/CommentServiceImpl.java
- src/main/java/EatPic/spring/domain/greetingMessage/controller/GreetingController.java
- src/main/java/EatPic/spring/domain/greetingMessage/service/GreetingService.java
- src/main/java/EatPic/spring/domain/reaction/controller/ReactionRestController.java
- src/main/java/EatPic/spring/domain/reaction/service/ReactionService.java
- src/main/java/EatPic/spring/domain/reaction/service/ReactionServiceImpl.java
- src/main/java/EatPic/spring/domain/reportHistory/controller/ReportController.java
- src/main/java/EatPic/spring/domain/reportHistory/service/ReportService.java
- src/main/java/EatPic/spring/domain/reportHistory/service/ReportServiceImpl.java
- src/main/java/EatPic/spring/domain/user/controller/UserRestController.java
- src/main/java/EatPic/spring/domain/user/service/UserBadgeService.java
- src/main/java/EatPic/spring/domain/user/service/UserService.java
- src/main/java/EatPic/spring/domain/user/service/UserServiceImpl.java
> refactor: 로그인한 유저 수정

- src/main/java/EatPic/spring/domain/user/controller/UserRestController.java
- src/main/java/EatPic/spring/domain/user/converter/UserConverter.java
- src/main/java/EatPic/spring/domain/user/dto/response/UserResponseDTO.java
- src/main/java/EatPic/spring/domain/user/repository/UserFollowRepository.java
- src/main/java/EatPic/spring/domain/user/service/UserService.java
- src/main/java/EatPic/spring/domain/user/service/UserServiceImpl.java
- src/main/java/EatPic/spring/global/common/code/status/ErrorStatus.java
> Feat: 팔로잉/팔로잉 취소 api

- src/main/java/EatPic/spring/domain/calendar/controller/CalendarController.java
- src/main/java/EatPic/spring/domain/calendar/service/CalendarService.java
- src/main/java/EatPic/spring/domain/card/controller/CardController.java
- src/main/java/EatPic/spring/domain/card/service/CardService.java
- src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
- src/main/java/EatPic/spring/domain/notification/controller/NotificationController.java
- src/main/java/EatPic/spring/domain/notification/service/NotificationService.java
- src/main/java/EatPic/spring/domain/user/controller/UserBadgeController.java
- src/main/java/EatPic/spring/domain/user/service/UserBadgeService.java
>  #132 
카드 생성 api login
카드 수정 api login
캘린더 조회 api login
알림 관련 api 3개 login처리
뱃지 홈화면 이행률순 조회 login
뱃지 상세조회 login
> login 처리 중복 검사 안하도록 되도록이면 객체 넘기는 방식으로 해주세요!
> Refactor: 로그인 처리 관련 수정

- src/main/java/EatPic/spring/domain/user/converter/UserConverter.java
- src/main/java/EatPic/spring/domain/user/dto/response/SignupResponseDTO.java
- src/main/java/EatPic/spring/domain/user/service/UserServiceImpl.java
> #108
> 회원 가입 시, DTO 응답을 Converter를 통한 응답으로 변경
> 500 error -> 400 error로 수정
> "회원 가입이 완료되었습니다." message 삭제
-> 수정 전
-> 수정 후
-> message 삭제
> Refactor: 에러 처리 및 UserConverter 수정

- src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
- src/main/java/EatPic/spring/domain/user/controller/UserRestController.java
- src/main/java/EatPic/spring/domain/user/entity/User.java
- src/main/java/EatPic/spring/domain/user/service/UserService.java
- src/main/java/EatPic/spring/domain/user/service/UserServiceImpl.java
> ex) #124 
> 마이페이지 관련 작업 입니다.
> 저장된 계정 데이터에서 추후에 유저 프로필 이미지를 변경합니다.
> Feat: 유저 프로필 이미지 수정 API

- src/main/java/EatPic/spring/domain/bookmark/repository/BookmarkRepository.java
- src/main/java/EatPic/spring/domain/card/controller/CardController.java
- src/main/java/EatPic/spring/domain/card/repository/CardHashtagRepository.java
- src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
- src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
- src/main/java/EatPic/spring/domain/comment/repository/CommentRepository.java
- src/main/java/EatPic/spring/domain/reaction/repository/ReactionRepository.java
> 138
성능 비교하는법 몰라서 로그 찍어봤는데 라인 수 줄었으니까 개선이 됐겠죠....?
>
> Refactor: 피드조회 쿼리 개선

- src/main/java/EatPic/spring/domain/card/controller/CardController.java
- src/main/java/EatPic/spring/domain/card/dto/request/CardCreateRequest.java
- src/main/java/EatPic/spring/domain/card/service/CardService.java
- src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
> ex) #139 
> 픽카드 기록하기 request body 수정!! 하하 얏호!!
> Refactor: 픽카드 기록하기 파라미터로 받아오는 request 수정

- src/main/java/EatPic/spring/domain/card/dto/response/CardResponse.java
- src/main/java/EatPic/spring/domain/reaction/controller/ReactionRestController.java
> ex) #143 
> 피드조회 res에 nameId 추가
> Refactor: nameId 추가

- src/main/java/EatPic/spring/domain/card/controller/CardController.java
- src/main/java/EatPic/spring/domain/card/converter/CardConverter.java
- src/main/java/EatPic/spring/domain/card/dto/response/CardResponse.java
- src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
- src/main/java/EatPic/spring/domain/card/service/CardService.java
- src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
>  #155 
카드 삭제 시 응답으로 성공메세지와 카드 아이디 반환
여러 api에서 카드 조회 시, 삭제된 카드는 조회되지 않도록 수정
> 다른 부분에서도 카드 조회하는 메서드 사용되고 있다면, 이 PR을 참고해서 삭제된 카드는 조회되지 않도록 메서드 다시 설정해주세요
> Refactor: card delete 관련 코드 수정

- src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
- src/main/java/EatPic/spring/domain/card/service/SearchServiceImpl.java
> ex) #이슈번호, #이슈번호
* 이전 쿼리에서 불필요한 페치조인 있어서 삭제했습니다.
* 해시태그 별 작성된 카드 수 조회 로직에서 card 카운트하는 부분 수정했습니다.
* getHashtagInFollow랑 getHashtagInAll에서 slice -> dto 부분이 겹쳐서 getGetHashtagListResponseDto 메소드 추출했습니다.(인텔리제이가 해줌)
>
> refactor: SearchService 쿼리 최적화

- src/main/java/EatPic/spring/domain/card/controller/SearchController.java
- src/main/java/EatPic/spring/domain/card/service/SearchServiceImpl.java
- src/main/java/EatPic/spring/domain/user/repository/UserRepository.java
> 182
목록 조회 화면 처음에 들어갔을 때 검색하기 전에도 목록이 떠야 하므로 query를 null 허용 했고 이에 따른 repository메소드 @Query
부분도 수정했습니다 
>
> Refactor: 팔로워 목록 로직 수정, query 없는 경우 추가

- src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
> Refactor: findCardsWithReactionCountOver1 쿼리 수정

- src/main/java/EatPic/spring/domain/user/controller/UserController.java
- src/main/java/EatPic/spring/domain/user/dto/response/RefreshTokenResponseDTO.java
- src/main/java/EatPic/spring/domain/user/repository/UserRepository.java
- src/main/java/EatPic/spring/domain/user/service/UserService.java
- src/main/java/EatPic/spring/domain/user/service/UserServiceImpl.java
- src/main/java/EatPic/spring/global/config/Properties/JwtProperties.java
- src/main/java/EatPic/spring/global/config/jwt/JwtTokenProvider.java
> Feat: refresh token 재발급 

- src/main/java/EatPic/spring/domain/user/repository/UserRepository.java
- src/main/java/EatPic/spring/domain/user/service/UserServiceImpl.java
> ex) #187 
> - 로그인 기능에서 발생하던 서버 500 에러 문제 해결
> - JPA 쿼리 파라미터에 @Param 어노테이션을 추가하여 명명된 파라미터 문제 수정
> - 서비스 메서드에 @Transactional 어노테이션을 붙여 트랜잭션 문제 해결
> Bug: 메서드에 @Transactional 어노테이션을 추가
